### ISSUE TITLE
如何转换V3版本

### ISSUE THREAD

**Issue by xyx361100238** [yeyupiaoling/Whisper-Finetune#47]
使用ct2-transformers-converter如何转换V3版本的格式，出现错误提示：
Traceback (most recent call last):
  File "/home/anaconda3/envs/Whisper-finetune/bin/ct2-transformers-converter", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/ctranslate2/converters/transformers.py", line 1771, in main
    converter.convert_from_args(args)
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/ctranslate2/converters/converter.py", line 50, in convert_from_args
    return self.convert(
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/ctranslate2/converters/converter.py", line 89, in convert
    model_spec = self._load()
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/ctranslate2/converters/transformers.py", line 98, in _load
    config = transformers.AutoConfig.from_pretrained(
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1034, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/anaconda3/envs/Whisper-finetune/lib/python3.9/site-packages/transformers/utils/hub.py", line 400, in cached_file
    raise EnvironmentError(
OSError: whisper-large-v3 does not appear to have a file named config.json. Checkout 'https://huggingface.co//whisper-large-v3/None' for available files.

**Comment by yeyupiaoling** [comment]
你看看你的版本是不是没升到最新版本

**Comment by yeyupiaoling** [comment]
你这个错误好像是路径问题吧？

**Comment by xyx361100238** [comment]
确定了是文件的问题，我全部重新下载就可以了（如果从AI-ModelScope下载文件一定要跟huggingface上文件列表进行确认）
